[project]
org-name = "whizsid"
version = "0.1.0"
license = ["MIT"]
authors = ["WhizSid"]
repository = "https://github.com/whizsid/angelina"
keywords = ["ballerina", "ORM", "database", "hibernate","eloquent"]

[dependencies]
[platform]
target = "java8"

[[platform.libraries]]
artafactId = "mysql-connector-java"
version = "8.0.17"
path = "./drivers/mysql-connector-java-8.0.21.jar"
groupId = "mysql"